<?php

// This file is automatically generated and modified by phpMyBackupPro 2.5

$CONF['sql_user']=ue('root');
$CONF['sql_host']=ue('localhost');
$CONF['sql_db']=ue('lugrawibe');
$CONF['ftp_use']=ue('0');
$CONF['email_use']=ue('0');
$CONF['sitename']=ue('example.com');
$CONF['lang']=ue('english');
$CONF['import_error']=ue('1');
$CONF['no_login']=ue('0');
$CONF['login']=ue('0');
$CONF['dir_backup']=ue('0');
$CONF['dir_rec']=ue('1');
$CONF['email']=ue('lugrawibe@gmail.com');
$CONF['ftp_pasv']=ue('1');
$CONF['ftp_del']=ue('1');
$CONF['ftp_server']=ue('example.com');
$CONF['ftp_user']=ue('');
$CONF['ftp_port']=ue('21');
$CONF['date']=ue('%d.%m.%Y %H:%M Uhr');
$CONF['del_time']=ue('3');
$CONF['del_number']=ue('5');
$CONF['timelimit']=ue('30');
$CONF['confirm']=ue('1');
$CONF['stylesheet']=ue('standard');
$CONF['ftp_path']=ue('');
$CONF['ftp_passwd']=ue('');
$CONF['sql_passwd']=ue('');

$PMBP_SYS_VAR['last_scheduled']=ue('');
$PMBP_SYS_VAR['this_login']=ue('29.03.2016 18:18 Uhr (IP: 127.0.0.1)');
$PMBP_SYS_VAR['last_login']=ue('28.03.2016 18:46 Uhr (IP: 127.0.0.1)');
$PMBP_SYS_VAR['dir_lists']=ue('1');
$PMBP_SYS_VAR['memory_limit']=ue('4000000');
$PMBP_SYS_VAR['except_tables']=ue('');
$PMBP_SYS_VAR['scheduled_debug']=ue('0');
$PMBP_SYS_VAR['schedule_all_dbs']=ue('0');
$PMBP_SYS_VAR['ftp_timeout']=ue('10');
$PMBP_SYS_VAR['dir_email_backup']=ue('0');
$PMBP_SYS_VAR['C_disable_config']=ue('0');
$PMBP_SYS_VAR['C_disable_sqlquery']=ue('0');
$PMBP_SYS_VAR['B_backup_chmod']=ue('0700');
$PMBP_SYS_VAR['F_dbs']=ue('lugrawibe');
$PMBP_SYS_VAR['F_comment']=ue('wilder dice hola comentando by wil');
$PMBP_SYS_VAR['F_tables']=ue('on');
$PMBP_SYS_VAR['F_data']=ue('on');
$PMBP_SYS_VAR['F_drop']=ue('on');
$PMBP_SYS_VAR['F_compression']=ue('');
$PMBP_SYS_VAR['F_ftp_dirs']=ue('');
$PMBP_SYS_VAR['F_ftp_dirs_2']=ue('');
$PMBP_SYS_VAR['F_packed']=ue('');
$PMBP_SYS_VAR['F_updates']=ue('1');
$PMBP_SYS_VAR['F_ffadd']=ue('1');
$PMBP_SYS_VAR['EXS_scheduled_file']=ue('???.php');
$PMBP_SYS_VAR['EXS_scheduled_dir']=ue('0');
$PMBP_SYS_VAR['EXS_period']=ue('');

?>